### ISSUE TITLE
360 renders

### ISSUE THREAD

**Issue by Zandy2** [icosa-gallery/open-brush-docs#2]
Trying to render a 360 video using steam beta (1st option, prerelease, etc).  Noticed the bat file now states HQ render.  Chose option 5 as usual and getting a blank render.  It seems that the process does not load before rendering.  Getting a blank output.

**Comment by andybak** [comment]
You probably meant to post this here: https://github.com/icosa-gallery/open-brush/issues

(i.e the issues for the app itself, not the docs)

I don't think I can move an issue to a different repo. Would you mind reposting it?

Also - maybe make the title more descriptive of the problem: "Getting a blank output when rendering 360 video on the beta" or similar.
